# /etc/ipsec.conf - Libreswan IPsec configuration file

config setup
	logfile=/tmp/pluto.log
	logtime=no
	logappend=no
	plutodebug=all
	dumpdir=/tmp

conn westnet-eastnet-ikev2
	left=192.1.2.45
	leftid="C=CA, ST=Ontario, L=Toronto, O=Libreswan, OU=Test Department, CN=west.testing.libreswan.org, E=user-west@testing.libreswan.org"
	leftsubnet=192.0.1.0/24
	leftcert=west
	right=192.1.2.23
	rightsubnet=192.0.2.0/24
	rightid="C=CA, ST=Ontario, L=Toronto, O=Libreswan, OU=Test Department, CN=east.testing.libreswan.org, E=user-east@testing.libreswan.org"
	authby=mldsa
	leftsendcert=always
	rightsendcert=always
	fragmentation=yes
	retransmit-timeout=10
